version: '3.1'

services:
  master:
    build:
      context: .
      args:
        version: 2.4.3
    container_name: spark-master
    command: master
    ports:
      - 8080:8080
      - 7077:7077

  worker1:
    build:
      context: .
      args:
        version: 2.4.3
    container_name: spark-worker1
    command: worker spark://master:7077
    depends_on:
      - master
    ports:
      - 8081:8081
    environment:
      - SPARK_WORKER_MEMORY=1g

